### ISSUE TITLE
Cannot convert react.d.ts

### ISSUE THREAD

**Issue by kengorab** [Kotlin/ts2kt#42] opened 2017-03-22 02:05 UTC
I'm trying to convert the React type declaration file, but am coming across some errors.

I run
```
$ node_modules/.bin/ts2kt -d headers node_modules/@types/react/index.d.ts
```

But this gets output:
```
Converting node_modules/@types/react/index.d.ts
ts2kt: "NamespaceExportDeclaration" kind unsupported yet here! (node_modules/@types/react/index.d.ts:7:16 to 8:27)
/Users/kengorab/code/kotlinjs-test/node_modules/ts2kt/node_modules/typescript/lib/typescript.js:5738
        return identifier.length >= 3 && identifier.charCodeAt(0) === 95 /* _ */ && identifier.charCodeAt(1) === 95 /* _ */ && identifier.charCodeAt(2) === 95 /* _ */ ? identifier.substr(1) : identifier;
                         ^

TypeError: Cannot read property 'length' of undefined
    at Object.unescapeIdentifier (/Users/kengorab/code/kotlinjs-test/node_modules/ts2kt/node_modules/typescript/lib/typescript.js:5738:26)
    at TsInterfaceToKt.TsClassifierToKt.visitPropertyDeclaration_qnxew1$ (/Users/kengorab/code/kotlinjs-test/node_modules/ts2kt/ts2kt.js:952:35)
    at visitNode (/Users/kengorab/code/kotlinjs-test/node_modules/ts2kt/ts2kt.js:3942:15)
    at /Users/kengorab/code/kotlinjs-test/node_modules/ts2kt/ts2kt.js:3897:7
    at visitEachNode (/Users/kengorab/code/kotlinjs-test/node_modules/ts2kt/node_modules/typescript/lib/typescript.js:8343:30)
    at Object.forEachChild (/Users/kengorab/code/kotlinjs-test/node_modules/ts2kt/node_modules/typescript/lib/typescript.js:8429:24)
    at forEachChild_0 (/Users/kengorab/code/kotlinjs-test/node_modules/ts2kt/ts2kt.js:3901:24)
    at ObjectTypeToKotlinTypeMapperImpl.getKotlinTypeForObjectType_29gnwt$ (/Users/kengorab/code/kotlinjs-test/node_modules/ts2kt/ts2kt.js:438:5)
    at toKotlinType_3 (/Users/kengorab/code/kotlinjs-test/node_modules/ts2kt/ts2kt.js:3666:23)
    at toKotlinType_0 (/Users/kengorab/code/kotlinjs-test/node_modules/ts2kt/ts2kt.js:3718:16)
```

I'm using `typescript@2.2.1` in my project's dependencies, but I noticed the `ts2kt` project depends on `typescript@2.0.10`; I don't know if that's related, but I figured I'd mention that the tool is using an outdated version, and some type definitions which get updated frequently (React being one of them) might not work with older versions.

**Comment by ScottPierce** [comment] 2017-03-30 02:58
I'm getting the exact same error.

**Comment by bashor** [comment] 2017-03-30 10:53
looks like duplicate of #38

**Comment by denisidoro** [comment] 2017-04-14 11:37
Apparently, if you disable exportedByAssignment check, it works: https://github.com/Kotlin/ts2kt/pull/10

**Closed** 2017-06-26 21:17 UTC
Labels: g: Crash, t: Bug
